### ISSUE TITLE
Help with Lab11

### ISSUE THREAD

**Issue by LizaShkuropatova** [oleksandrblazhko/ai-214-shkuropatova#29]
Доброго вечора, я виконую лаб.11 та в мене є питання:

Перше завдання 
мій репозиторій - https://github.com/LizaShkuropatova/Laboratory-work-11

DataSchema.sql: 
https://github.com/LizaShkuropatova/Laboratory-work-11/blob/main/DataSchema.sql: 

DataSchemaCodeConvention.yml:
https://github.com/LizaShkuropatova/Laboratory-work-11/blob/main/.github/workflows/DataSchemaCodeConvention.yml

Результат із помилками:
https://github.com/LizaShkuropatova/Laboratory-work-11/actions/runs/6973184551

Дуже багато помилок мені виводить і я намагалась змінити схему та сценарій, повністю заново переробила, але все одно помилки ті ж самі. В чому мої помилки чи створити схему JSON?

**Comment by oleksandrblazhko** [comment]
Доброго вечора.
Є опис правил та номери помилок.
Зараз у вас більшість помилок пов'язано з:
1) https://docs.sqlfluff.com/en/stable/rules.html#rule-capitalisation.identifiers
2) https://docs.sqlfluff.com/en/stable/rules.html#rule-layout.spacing
Подивіться, що увас може там бути.
